services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring-boot-redis-token-management-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redis_token_database
      PGDATA: /data/postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis-spring-boot-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
