spring.application.name=redis-token-management

#--DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

#Jpa/hibernate properties
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#jwt Confugaration
jwt.secret=mlvQhpGm0RWcIkeL1qmWWtpR0WrD6c8eRrP/hSk72p4=
jwt.issuer=sarinkejohn.com
jwt.expiration=3600000
jwt.refresh-expiration=86400000


#Redis conf
spring.data.redis.host=redis
spring.data.redis.port=6379
